# Generated by Django 4.1.13 on 2024-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferred_currency', models.CharField(max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
