# Generated by Django 4.1.13 on 2024-11-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Sr_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
