# Generated by Django 4.1.13 on 2024-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
