# Generated by Django 4.1.13 on 2024-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
