# Generated by Django 4.1.13 on 2024-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
