# Generated by Django 4.1.13 on 2024-11-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_remove_income_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AddField(
            model_name='income',
            name='Sr_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
