# Generated by Django 4.1.13 on 2024-11-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_remove_income_id_income_sr_no_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Sr_no',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
