# Generated by Django 4.1.13 on 2024-11-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
