# Generated by Django 4.1.13 on 2024-11-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
